# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.


name: Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.1.2']


    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Install dplyr package
        run: Rscript -e 'install.packages("dplyr", dependencies = TRUE)'
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript Deploy.R
