# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: Deploy

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* * * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v3
      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@f57f1301a053485946083d7a45022b278929a78a
        with:
          r-version: ${{ matrix.r-version }}
      - name: Install dependencies
        run: |
          install.packages(c("dplyr", "rtweet", "rvest", "mongolite", "xml", "xml2"))
        shell: Rscript {0}
      - name: Create and post tweet
        run: Rscript Deploy.R       

